# BuildLibffi.cmake - Build libffi from upstream source
#
# We FetchContent libffi/libffi at a pinned tag and compile it ourselves
# instead of relying on third-party CMake forks (each had its own bugs).
#
# Inputs (set by caller):
#   libffi_SOURCE_DIR  - populated by FetchContent_MakeAvailable(libffi)
#
# Outputs:
#   libffi (static target) - public include dir contains ffi.h, ffitarget.h,
#                            fficonfig.h. FFI_STATIC_BUILD propagates to
#                            consumers so MSVC drops the dllimport decoration.
#   LIBFFI_AVAILABLE       - set TRUE on success.
#
# Supported platforms:
#   Linux x86_64
#   Linux ARM64
#   Windows x86_64  (MSVC + Clang + MinGW)
#   macOS ARM64
#
# Set -DFERN_BUILD_LIBFFI=OFF to skip libffi entirely.

set(LIBFFI_SRC ${libffi_SOURCE_DIR})
set(LIBFFI_GEN ${CMAKE_BINARY_DIR}/_deps/libffi-gen)
file(MAKE_DIRECTORY ${LIBFFI_GEN}/include)

set(LIBFFI_VERSION 3.5.2)

# === Detect target platform ===
set(_libffi_target "")
set(_libffi_targetdir "")

if(CMAKE_SYSTEM_PROCESSOR MATCHES "x86_64|amd64|AMD64")
    if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
        set(_libffi_target X86_64)
        set(_libffi_targetdir x86)
    elseif(WIN32)
        set(_libffi_target X86_WIN64)
        set(_libffi_targetdir x86)
    endif()
elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "aarch64|arm64|ARM64")
    if(APPLE OR CMAKE_SYSTEM_NAME STREQUAL "Linux")
        set(_libffi_target AARCH64)
        set(_libffi_targetdir aarch64)
    elseif(WIN32)
        set(_libffi_target ARM_WIN64)
        set(_libffi_targetdir aarch64)
    endif()
endif()

if(NOT _libffi_target)
    message(FATAL_ERROR
        "BuildLibffi: ${CMAKE_SYSTEM_NAME}/${CMAKE_SYSTEM_PROCESSOR} is not "
        "supported. Extend the platform dispatch table in cmake/BuildLibffi.cmake, "
        "or set -DFERN_BUILD_LIBFFI=OFF to skip libffi entirely.")
endif()

# === Generate fficonfig.h ===
# libffi's autotools build runs ./configure to detect HAVE_* features. Since
# we know which platforms we support, we hardcode per-platform values.
if(_libffi_target STREQUAL "X86_64")
    file(WRITE ${LIBFFI_GEN}/include/fficonfig.h [=[
/* Auto-generated by Fern's BuildLibffi.cmake. Do not edit. */
#define EH_FRAME_FLAGS "a"
#define HAVE_ALLOCA 1
#define HAVE_AS_ASCII_PSEUDO_OP 1
#define HAVE_AS_STRING_PSEUDO_OP 1
#define HAVE_AS_X86_PCREL 1
#define HAVE_HIDDEN_VISIBILITY_ATTRIBUTE 1
#define HAVE_INTTYPES_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define PACKAGE "libffi"
#define PACKAGE_NAME "libffi"
#define PACKAGE_VERSION "3.5.2"
#define SIZEOF_DOUBLE 8
#define SIZEOF_LONG_DOUBLE 16
#define SIZEOF_SIZE_T 8
#define STDC_HEADERS 1
#define VERSION "3.5.2"

#ifdef HAVE_HIDDEN_VISIBILITY_ATTRIBUTE
# ifdef LIBFFI_ASM
#  define FFI_HIDDEN(name) .hidden name
# else
#  define FFI_HIDDEN __attribute__ ((visibility ("hidden")))
# endif
#else
# ifdef LIBFFI_ASM
#  define FFI_HIDDEN(name)
# else
#  define FFI_HIDDEN
# endif
#endif
]=])
elseif(_libffi_target STREQUAL "X86_WIN64")
    file(WRITE ${LIBFFI_GEN}/include/fficonfig.h [=[
/* Auto-generated by Fern's BuildLibffi.cmake. Do not edit. */
#define HAVE_ALLOCA 1
#define HAVE_INTTYPES_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define PACKAGE "libffi"
#define PACKAGE_NAME "libffi"
#define PACKAGE_VERSION "3.5.2"
#define SIZEOF_DOUBLE 8
#define SIZEOF_LONG_DOUBLE 8
#define SIZEOF_SIZE_T 8
#define STDC_HEADERS 1
#define VERSION "3.5.2"

#ifdef LIBFFI_ASM
# define FFI_HIDDEN(name)
#else
# define FFI_HIDDEN
#endif
]=])
elseif(_libffi_target STREQUAL "AARCH64" AND APPLE)
    file(WRITE ${LIBFFI_GEN}/include/fficonfig.h [=[
/* Auto-generated by Fern's BuildLibffi.cmake. Do not edit. */
#define HAVE_ALLOCA 1
#define HAVE_HIDDEN_VISIBILITY_ATTRIBUTE 1
#define HAVE_INTTYPES_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define FFI_EXEC_TRAMPOLINE_TABLE 1
#define PACKAGE "libffi"
#define PACKAGE_NAME "libffi"
#define PACKAGE_VERSION "3.5.2"
#define SIZEOF_DOUBLE 8
#define SIZEOF_LONG_DOUBLE 8
#define SIZEOF_SIZE_T 8
#define STDC_HEADERS 1
#define VERSION "3.5.2"

#ifdef HAVE_HIDDEN_VISIBILITY_ATTRIBUTE
# ifdef LIBFFI_ASM
#  define FFI_HIDDEN(name) .private_extern name
# else
#  define FFI_HIDDEN __attribute__ ((visibility ("hidden")))
# endif
#else
# ifdef LIBFFI_ASM
#  define FFI_HIDDEN(name)
# else
#  define FFI_HIDDEN
# endif
#endif
]=])
elseif(_libffi_target STREQUAL "AARCH64")
    # Linux ARM64
    file(WRITE ${LIBFFI_GEN}/include/fficonfig.h [=[
/* Auto-generated by Fern's BuildLibffi.cmake. Do not edit. */
#define EH_FRAME_FLAGS "a"
#define HAVE_ALLOCA 1
#define HAVE_HIDDEN_VISIBILITY_ATTRIBUTE 1
#define HAVE_INTTYPES_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define PACKAGE "libffi"
#define PACKAGE_NAME "libffi"
#define PACKAGE_VERSION "3.5.2"
#define SIZEOF_DOUBLE 8
#define SIZEOF_LONG_DOUBLE 16
#define SIZEOF_SIZE_T 8
#define STDC_HEADERS 1
#define VERSION "3.5.2"

#ifdef HAVE_HIDDEN_VISIBILITY_ATTRIBUTE
# ifdef LIBFFI_ASM
#  define FFI_HIDDEN(name) .hidden name
# else
#  define FFI_HIDDEN __attribute__ ((visibility ("hidden")))
# endif
#else
# ifdef LIBFFI_ASM
#  define FFI_HIDDEN(name)
# else
#  define FFI_HIDDEN
# endif
#endif
]=])
elseif(_libffi_target STREQUAL "ARM_WIN64")
    file(WRITE ${LIBFFI_GEN}/include/fficonfig.h [=[
/* Auto-generated by Fern's BuildLibffi.cmake. Do not edit. */
#define HAVE_ALLOCA 1
#define HAVE_INTTYPES_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define PACKAGE "libffi"
#define PACKAGE_NAME "libffi"
#define PACKAGE_VERSION "3.5.2"
#define SIZEOF_DOUBLE 8
#define SIZEOF_LONG_DOUBLE 8
#define SIZEOF_SIZE_T 8
#define STDC_HEADERS 1
#define VERSION "3.5.2"

#ifdef LIBFFI_ASM
# define FFI_HIDDEN(name)
#else
# define FFI_HIDDEN
#endif
]=])
endif()

# === Generate ffi.h from ffi.h.in ===
set(VERSION ${LIBFFI_VERSION})
set(FFI_VERSION_STRING "${LIBFFI_VERSION}")
set(FFI_VERSION_NUMBER 30502)
set(TARGET ${_libffi_target})
if(_libffi_target STREQUAL "X86_WIN64"
        OR _libffi_target STREQUAL "ARM_WIN64"
        OR (_libffi_target STREQUAL "AARCH64" AND APPLE))
    set(HAVE_LONG_DOUBLE 0)        # Windows + macOS: long double == double
else()
    set(HAVE_LONG_DOUBLE 1)
endif()
if(_libffi_target STREQUAL "AARCH64" AND APPLE)
    set(FFI_EXEC_TRAMPOLINE_TABLE 1)
else()
    set(FFI_EXEC_TRAMPOLINE_TABLE 0)
endif()
configure_file(
    ${LIBFFI_SRC}/include/ffi.h.in
    ${LIBFFI_GEN}/include/ffi.h
    @ONLY
)

# Copy the arch-specific ffitarget.h into the public include dir.
file(COPY ${LIBFFI_SRC}/src/${_libffi_targetdir}/ffitarget.h
     DESTINATION ${LIBFFI_GEN}/include)

# === Source list ===
set(LIBFFI_SOURCES
    ${LIBFFI_SRC}/src/closures.c
    ${LIBFFI_SRC}/src/prep_cif.c
    ${LIBFFI_SRC}/src/types.c
    ${LIBFFI_SRC}/src/raw_api.c
    ${LIBFFI_SRC}/src/java_raw_api.c
    ${LIBFFI_SRC}/src/tramp.c
)

if(_libffi_target STREQUAL "X86_64")
    list(APPEND LIBFFI_SOURCES
        ${LIBFFI_SRC}/src/x86/ffi64.c
        ${LIBFFI_SRC}/src/x86/unix64.S
    )
elseif(_libffi_target STREQUAL "AARCH64")
    list(APPEND LIBFFI_SOURCES
        ${LIBFFI_SRC}/src/aarch64/ffi.c
        ${LIBFFI_SRC}/src/aarch64/sysv.S
    )
elseif(_libffi_target STREQUAL "X86_WIN64")
    list(APPEND LIBFFI_SOURCES ${LIBFFI_SRC}/src/x86/ffiw64.c)

    if(MSVC)
        # MSVC needs win64_intel.S preprocessed by cl.exe (Intel syntax) then
        # assembled by ml64. We do the preprocess at configure time since the
        # source is fixed at the libffi tag.
        set(_libffi_intel_asm ${LIBFFI_GEN}/win64_intel.asm)
        message(STATUS "BuildLibffi: preprocessing win64_intel.S with cl /EP")
        execute_process(
            COMMAND ${CMAKE_C_COMPILER} /nologo /EP
                    /I${LIBFFI_GEN}/include
                    /I${LIBFFI_SRC}/include
                    /I${LIBFFI_SRC}/src
                    ${LIBFFI_SRC}/src/x86/win64_intel.S
            OUTPUT_FILE ${_libffi_intel_asm}
            RESULT_VARIABLE _libffi_pp_result
        )
        if(NOT _libffi_pp_result EQUAL 0)
            message(FATAL_ERROR
                "BuildLibffi: failed to preprocess win64_intel.S "
                "(exit ${_libffi_pp_result}).")
        endif()
        list(APPEND LIBFFI_SOURCES ${_libffi_intel_asm})
        enable_language(ASM_MASM)
    else()
        # Clang and MinGW take the AT&T-syntax win64.S directly via their
        # integrated assembler / GAS.
        list(APPEND LIBFFI_SOURCES ${LIBFFI_SRC}/src/x86/win64.S)
        enable_language(ASM)
    endif()
elseif(_libffi_target STREQUAL "ARM_WIN64")
    list(APPEND LIBFFI_SOURCES ${LIBFFI_SRC}/src/aarch64/ffi.c)
    if(MSVC)
        # Windows ARM64 + MSVC needs the armasm64 preprocess+assemble dance.
        # Same shape as the x86 cl /EP + ml64 path but armasm64 has its own
        # syntax and we'd need to compile to .obj at configure time (CMake's
        # ASM_MARMASM language was added in 3.26 and we target 3.18).
        message(FATAL_ERROR
            "BuildLibffi: Windows ARM64 + MSVC is not yet implemented. "
            "Needs the armasm64 preprocess+assemble dance. "
            "Use Clang on Windows ARM64 in the meantime, or set "
            "-DFERN_BUILD_LIBFFI=OFF to skip libffi.")
    else()
        # Clang/MinGW on Windows ARM64 use the GAS-syntax sysv.S — same as
        # Linux/macOS ARM64. Internal #ifdefs in the .S file handle the ABI
        # differences.
        list(APPEND LIBFFI_SOURCES ${LIBFFI_SRC}/src/aarch64/sysv.S)
        enable_language(ASM)
    endif()
endif()

# === Define target ===
if(NOT _libffi_target STREQUAL "X86_WIN64" OR NOT MSVC)
    enable_language(ASM)
endif()

add_library(libffi STATIC ${LIBFFI_SOURCES})

target_include_directories(libffi
    PUBLIC ${LIBFFI_GEN}/include
    PRIVATE
        ${LIBFFI_SRC}/include
        ${LIBFFI_SRC}/src
)

target_compile_definitions(libffi
    PRIVATE FFI_BUILDING        # we are compiling libffi sources, not consuming
    PUBLIC  FFI_STATIC_BUILD    # statically linked: drop MSVC dllimport on ffi.h
)
set_target_properties(libffi PROPERTIES POSITION_INDEPENDENT_CODE ON)

set(LIBFFI_AVAILABLE TRUE)
